options:
  logging: CLOUD_LOGGING_ONLY

steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: [
      'build',
      '-t',
      'us-central1-docker.pkg.dev/xenon-pager-460322-v3/flask-docker-repo/flask-api:latest',
      '.'
    ]
  - name: 'gcr.io/cloud-builders/docker'
    args: [
      'push',
      'us-central1-docker.pkg.dev/xenon-pager-460322-v3/flask-docker-repo/flask-api:latest'
    ]
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: 'gcloud'
    args: [
      'run',
      'deploy',
      'flask-api-service',
      '--image',
      'us-central1-docker.pkg.dev/xenon-pager-460322-v3/flask-docker-repo/flask-api:latest',
      '--region',
      'us-central1',
      '--platform',
      'managed',
      '--allow-unauthenticated',
      '--memory',
      '4Gi'
    ]

images:
  - 'us-central1-docker.pkg.dev/xenon-pager-460322-v3/flask-docker-repo/flask-api:latest'
