name: Deploy Streamlit App

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-deploy-streamlit:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Lint with flake8
      run: |
        pip install flake8
        flake8 --ignore=E203,E501,W605,F401,W293,W291 app.py models.py

    - name: Build Docker image
      run: |
        docker build -t flask-app -f Dockerfile .

    - name: Push to Azure (or other cloud)
      run: |
        echo "Here you would push Docker image to Azure Container Registry, Azure Web App, or run deployment commands"